title: FiskalHR Go - Croatian Fiscalization Library (Fiskalizacija)
description: >
  FiskalHR Go is an open-source Golang library designed for seamless integration with the Croatian fiscalization system in pure Go.
  <br>
  FiskalHR Go je open-source Golang modul dizajniran za jednostavnu integraciju s hrvatskim sustavom fiskalizacije u čistom Go jeziku.

theme: hacker

# Other optional configurations
show_downloads: false
google_analytics: 
